### PR TITLE
Updating master 

### PR DESCRIPTION
**Pull request by soazig**

### CODE REVIEW

**Comment by timothy1191xa** [comment]
the test has passed. do you want me to merge it?

**Comment by soazig** [comment]
Not yet, I am still fixing stuff not covered with test. I did not have time
to do the Makfike you sent me last night. Can you? I basically had to
finish the report by myself.

**Comment by timothy1191xa** [comment]
The thing is I'm not sure if like it will require to run something before scripts. so I just write makefile based on how many scripts we have. For example, linear and logistic regression analysis don't require others stuff, they can be run separately and the results can be achieved, but I don't know about other scripts.

**Comment by timothy1191xa** [comment]
@ye-zhi @lizhua @mingujo Please let me know if your scripts need to be taken care for the issue above.

**Comment by soazig** [comment]
Oh wait. I am doing a make file too for my analysis. I also need to update Min's stuff.
Just do your analysis and we should be fine.

**Pull request merged**
