### PR TITLE
Finished Log regression and testing for organize behavior data python file

### PR DESCRIPTION
**Pull request by mingujo**

### CODE REVIEW

**Comment by mingujo** [comment]
It's all set so its okay to merge with master

**Comment by mingujo** [comment]
yea i mean this travis should fail because i'm testing our ds005 dataset and our git repo does not have that lol.

**Comment by soazig** [comment]
Maybe you want to try the merge on Tests first ?
I am trying to keep this branch as a buffer to always be updated ahead of master.

**Comment by mingujo** [comment]
So the issue is, 

I made a test for organize_behavior_data.py
I can't test on ds114 because obviously that dataset doesn't have behavior data txt files.
Can I upload subject 2's behavior data txt files and test on them? 
Just to get a confirmation from you

@soazig

**Pull request closed without merging**
